[project]
name = "floresta-functional-tests"
version = "0.0.2"
description = "Collection of tools to help with functional testing of Floresta"
authors = [{name = "The Floresta Project Developers"}]
license = {text = "MIT"}
requires-python = ">=3.12"
dependencies = [
    "jsonrpclib>=0.2.1",
    "requests>=2.32.3",
    "black>=24.10.0",
    "pylint>=3.3.2",
]

[tool.hatch.build.targets.wheel]
packages = ["tests/test_framework"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
